In [2]:
import numpy as np
import copy
grid = [
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1]]

N=8
grid=np.zeros([N,N], dtype=int)
grid=grid.tolist()

def possible(grid, y, x):
    l = len(grid)
    
    for i in range(l):
        if grid[y][i] == 1:
            return False
        
    for i in range(l):
        if grid[i][x] == 1:
            return False
            
    for i in range(l):
        for j in range(l):
            if grid[i][j] == 1:
                if abs(i - y) == abs(j - x):
                    return False
    return True  
        
def solve(grid):
    l=len(grid) #length of our grid       
    
    for y in range(l): #for every row
        for x in range(l): #for every column
            if grid[y][x]==0: # we can place if there is no queen in given position
                if possible(grid,y,x): #if empty, check if we can place a queen
                    grid[y][x]=1 #if we can, then place it
                    solve(grid) #pass grid for recursive solution
                    if sum(sum(a) for a in grid)==l: #if there are 8 queens\n",
                        return grid #we are successful so return
                    grid[y][x]=0 #remove the previous placed queen
    return grid
        
Solution = solve(copy.deepcopy(grid))
print(np.matrix(Solution))

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
